[package]
name = "contiker-docker"
version = "0.1.0"
edition = "2024"

[dependencies]
bollard = "0.19"
tokio = { version = "1.48", features = [
  "macros",
  "rt-multi-thread",
], default-features = false }
