[package]
name = "contiker-wsl"
version = "0.1.0"
edition = "2024"

[dependencies]
wsl-api = "0.1.0"
anyhow.workspace = true
reqwest = { version = "0.12", features = ["blocking"] }
tempdir = "0.3.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
uuid = "1"
